const mensagens = [
"... que seu dia seja iluminado por tudo aquilo que faz sua alma sorrir.",
"... você merece toda a paz e toda a beleza que o mundo pode oferecer.",
"... hoje é um ótimo dia para acreditar mais uma vez em você.",
"... que a esperança encontre sempre um lugar quentinho no seu coração.",
"... você é mais forte do que imagina e mais especial do que percebe.",
"... que seu caminho seja leve como a paz que você merece.",
"... cada amanhecer é uma nova chance para ser feliz.",
"... suas pequenas vitórias também merecem celebração.",
"... nunca esqueça o quanto você é essencial.",
"... que sua semana seja guiada por amor e coragem.",
"... você carrega um universo bonito dentro de si.",
"... que a vida te surpreenda com carinho hoje.",
"... você merece o abraço mais sincero que a vida puder te dar.",
"... que a serenidade te acompanhe como uma brisa suave.",
"... lembre-se: você é motivo de alegria para o mundo.",
"... seu coração é uma casa onde mora a esperança.",
"... que a vida te traga aquilo que faz seus olhos brilharem.",
"... você é importante demais para desistir agora.",
"... que a calma encontre abrigo em você.",
"... existe beleza no seu jeito de existir.",
"... que seu dia comece com paz e termine com gratidão.",
"... você merece tudo o que é leve e verdadeiro.",
"... sua sensibilidade é uma força rara.",
"... tudo bem recomeçar — a vida é feita disso.",
"... que seu sorriso encontre motivos novos hoje.",
"... seus sonhos merecem ser cultivados.",
"... que seu coração receba o afeto que espalha.",
"... você é maior que seus medos.",
"... que os ventos soprem a seu favor.",
"... você já venceu tantas vezes — continue.",
"... seu brilho não depende da opinião de ninguém.",
"... que a paz seja sua companheira constante.",
"... existe luz mesmo nos dias nublados.",
"... você merece se sentir amado e acolhido.",
"... que hoje seu coração seja gentil consigo mesmo.",
"... a vida tem muito a te oferecer ainda.",
"... você é capaz de transformar dias comuns em dias especiais.",
"... permita-se ser feliz sem culpa.",
"... você merece tudo que é sincero.",
"... que a esperança esteja sempre viva em você.",
"... o mundo é mais bonito porque você existe.",
"... que sua jornada siga iluminada.",
"... você tem um coração precioso.",
"... que o amor te acompanhe nos detalhes do dia.",
"... você é feito de força suave.",
"... que o universo conspire ao seu favor.",
"... sua coragem é a prova de que você pode ir além.",
"... que a ternura encontre espaço no seu dia.",
"... tudo o que você precisa já está dentro de você.",

"... que hoje você descubra algo novo sobre si.",
"... você merece um dia cheio de paz.",
"... que suas escolhas sejam guiadas pelo amor.",
"... sua presença ilumina qualquer ambiente.",
"... que sua fé te sustente nos dias difíceis.",
"... você merece descanso e aconchego.",
"... que sua alma encontre liberdade.",
"... você é parte essencial da beleza do mundo.",
"... que seu dia seja leve como o vento.",
"... você merece caminhar sem pesos invisíveis.",
"... que o tempo te cure com carinho.",
"... você é feito de esperança e coragem.",
"... que seus sonhos encontrem espaço para crescer.",
"... você merece ser tratado com delicadeza.",
"... que seu coração seja sempre sua bússola.",
"... você é mais forte do que acredita.",
"... que sua vida seja cheia de descobertas bonitas.",
"... você merece carinho em dobro.",
"... que a vida abra caminhos onde você vê barreiras.",
"... você é coragem em forma de gente.",
"... que seu dia seja florido.",
"... você merece amor tranquilo.",
"... que a paz encontre morada no seu peito.",
"... você é singular e precioso.",
"... que seus passos te levem onde seu coração sorri.",
"... você merece abraços verdadeiros.",
"... que sua mente encontre silêncio quando precisar.",
"... você é fonte de luz.",
"... que o amor visite sua vida com gentileza.",
"... você merece dias calmos.",
"... que suas forças sejam renovadas hoje.",
"... você é uma alma bonita em movimento.",
"... que sua estrada seja iluminada.",
"... você merece estar em paz.",
"... que pequenas alegrias acompanhem seu dia.",
"... você é feito de possibilidades.",
"... que a vida te surpreenda para melhor.",
"... você merece carinho e cuidado.",

"... que seu coração se encha de esperança.",
"... você é mais forte do que os dias difíceis.",
"... que seu dia seja suave como um afeto.",
"... você merece florescer.",
"... que sua força cresça em silêncio.",
"... você é feito de luz.",
"... que a vida te envolva com amor.",
"... você merece a calmaria depois da tempestade.",
"... que seu sorriso tenha motivos novos.",
"... você é parte da poesia do mundo.",
"... que suas escolhas te aproximem da alegria.",
"... você merece descanso para a alma.",
"... que a vida seja generosa com você.",
"... você é doce como manhã de sol.",
"... que seu coração encontre aconchego.",
"... você merece tudo o que te faz bem.",
"... que bons ventos tragam novidades bonitas.",
"... você é feito de ternura.",
"... que seu caminho seja leve.",
"... você merece cada sorriso que espalha.",

"... que sua coragem brilhe hoje.",
"... você é importante mesmo quando esquece disso.",
"... que seu coração encontre paz profunda.",
"... você merece sonhos possíveis.",
"... que a vida te dê motivos para celebrar.",
"... você é força silenciosa.",
"... que a esperança se renove em você.",
"... você merece amor sem pressa.",
"... que sua alma sinta leveza.",
"... você é parte bonita da existência.",
"... que seus dias sejam iluminados.",
"... você merece recomeços suaves.",
"... que o amor te acompanhe hoje.",
"... você é mais especial do que sabe.",
"... que a paz esteja com você.",
"... você merece cada pequena alegria.",
"... que seu dia seja gentil.",
"... você é feito de poesia.",
"... que o universo cuide de você.",
"... você merece tudo o que é verdadeiro.",

"... que sua vida seja cheia de esperança.",
"... você é luz que não se apaga.",
"... que cada amanhecer te renove.",
"... você merece o melhor do mundo.",
"... que a calma visite seu coração.",
"... você é especial de um jeito só seu.",
"... que seu sorriso ilumine sua jornada.",
"... você merece ser amado profundamente.",
"... que sua alma se fortaleça.",
"... você é feito de amor.",
"... que seus passos sejam firmes.",
"... você merece ser feliz sem medo.",
"... que seu coração floresça.",
"... você é mais bonito quando acredita em si.",
"... que sua vida seja leve.",
"... você merece tudo o que te faz evoluir.",
"... que sua luz se mantenha acesa.",
"... você é importante para o mundo.",
"... que boas energias te acompanhem.",
"... você merece ser cuidado.",

"... que seu dia seja cheio de boas vibrações.",
"... você é feito de coragem.",
"... que a esperança dance dentro de você.",
"... você merece o carinho do universo.",
"... que seu caminho tenha flores.",
"... você é presença que acalma.",
"... que sua vida seja doce.",
"... você merece amor que acolhe.",
"... que seu coração encontre direção.",
"... você é parte da bondade do mundo.",
"... que a paz te encontre.",
"... você merece tudo o que te faz sorrir.",
"... que a vida te trate com ternura.",
"... você é feito de beleza.",
"... que seus dias sejam iluminados por esperança.",
"... você merece descanso e luz.",
"... que a vida abra portas para você.",
"... você é mais forte do que imagina.",
"... que a alegria te acompanhe.",
"... você merece amor verdadeiro.",

"... que seu dia seja cheio de ternura.",
"... você é luz até nos dias cinzentos.",
"... que pequenos milagres toquem sua vida.",
"... você merece caminhar em paz.",
"... que a vida seja suave com você.",
"... você é feito de sonhos lindos.",
"... que bons pensamentos ocupem sua mente.",
"... você merece carinho diário.",
"... que seu coração se fortaleça.",
"... você é parte da harmonia do mundo.",
"... que a vida cuide de você com amor.",
"... você merece ser feliz agora.",
"... que a calma preencha seu peito.",
"... você é feito de esperança silenciosa.",
"... que seu dia comece com luz.",
"... você merece coisas bonitas.",
"... que o universo te surpreenda.",
"... você é presença que inspira.",
"... que seus sonhos encontrem asas.",
"... você merece paz interior.",

"... que seu coração seja sempre casa para o amor.",
"... você é feito de possibilidades infinitas.",
"... que a vida te dê motivos para agradecer.",
"... você merece conforto emocional.",
"... que seu caminho seja iluminado.",
"... você é luz que guia.",
"... que seu dia tenha beleza.",
"... você merece gentileza.",
"... que seu coração encontre descanso.",
"... você é feito de fé.",
"... que a vida te abrace com carinho.",
"... você merece tudo o que é leve.",
"... que seu sorriso tenha motivo hoje.",
"... você é importante para quem te ama.",
"... que seus passos encontrem direção.",
"... você merece tranquilidade.",
"... que sua alma floresça em paz.",
"... você é feito de coragem tranquila.",
"... que o amor acompanhe seu dia.",
"... você merece tudo o que vibra amor.",

"... que seu coração encontre novas possibilidades.",
"... você é parte bonita do mundo.",
"... que a serenidade esteja com você.",
"... você merece sonhar alto.",
"... que a vida te encha de esperança.",
"... você é luz em forma de gente.",
"... que boas energias circulem em você.",
"... você merece descansar.",
"... que o amor seja sempre sua bússola.",
"... você é feito de beleza interior.",
"... que seu dia seja doce como mel.",
"... você merece ser ouvido.",
"... que sua alma encontre poesia.",
"... você é feito de brilho raro.",
"... que a vida te surpreenda com paz.",
"... você merece se sentir completo.",
"... que seu amanhã seja leve.",
"... você é parte da luz do mundo.",
"... que seu interior seja iluminado.",
"... você merece respirar fundo e sorrir.",

"... que a vida te abrace com infinitas possibilidades."
];
